declare namespace tools_app {
  let object_library: XmlElem<unknown | null>;
  function get_str_app_instance_id(applicationInstanceId: number): unknown;
  function get_application(object: string | number): ApplicationDocumentTopElem | null;
  function get_application_instance(object: string | number | ApplicationInstanceDocumentTopElem, applicationId: number): ApplicationInstanceDocumentTopElem;
  let cur_application: XmlElem<unknown | null>;
  function get_cur_application(applicationId: number, applicationInstanceId: number, objectId: number, objectTopElem: XmlTopElem): unknown;
  let cur_application_instance: XmlElem<unknown | null>;
  function get_cur_application_instance(applicationId: number, applicationInstanceId: number, objectId: number, objectTopElem: XmlTopElem): unknown;
  function set_cur_application_instance(applicationInstanceId: number, applicationInstanceTopElem: XmlTopElem): unknown;
  function create_application_instance(applicationId: number, returnId: boolean): unknown;
  function create_application_instance_object(objectName: string, objectFields: Object, applicationInstanceId: number, save: boolean): unknown;
  function get_cur_user_application_access_level(applicationId: number): unknown;
  function get_application_lib_url(applicationCode: string, applicationLibraryUrl: string, applicationVendor: string, applicationVendorLibrary: string, applicationLicType: string): unknown;
  function get_application_lib(object: Object): unknown;
  let cur_application_lib: XmlElem<unknown | null>;
  function get_cur_application_lib(applicationId: number, applicationInstanceId: number, objectId: number, objectTopElem: XmlTopElem): unknown;
  function convert_wvars_to_object(vars: Object, format: string, parentId: string, resultElem: Object): unknown;
  function get_settings(name: string, target: string, format: string, object: Object): unknown;
  function get_cur_settings(name: string, target: string, format: string, applicationId: number, applicationInstanceId: number, objectId: number, objectTopElem: XmlTopElem): unknown;
  function call_application_library_method(object: Object, methodName: string, arrMethod: unknown[]): unknown;
  function get_application_resources_list(object: Object): unknown;
  function get_application_resource(object: Object, resourceUrl: string): unknown;
  function package_application(object: Object): unknown;
  function clear_application_cache(applicationCode: string, componentCode: string): unknown;
  function get_application_ids(object: Object): unknown;
  function get_application_objects(object: Object, arrCatalogs: unknown[]): unknown;
  function save_cur_application_settings(lastApplication: unknown, newSettings: unknown): unknown;
  function save_application_settings(applicationId: number, settingsTopElem: XmlTopElem): unknown;
  function save_application_agents(aAgents: unknown, noWvars: boolean): unknown;
  function save_application_object(object: unknown, codeWvar: unknown, applicationId: number): unknown;
}
