declare namespace ms_tools {
  function get_url_from_catalog(catalogName: string, id: number): unknown;
  function view_open_doc(catalogName: string, id: number, topElem: unknown): unknown;
  function view_delete_doc(catalogName: unknown): unknown;
  function raise_system_event(code: unknown, systemEventId: number, objectDocId: number, objectDoc: unknown): unknown;
  function raise_system_event_env(systemEventId: number | string, params: Object): unknown;
  let notes_var: XmlElem<unknown | null>;
  function notes_verify_password(clearPassword: unknown, hashPassword: unknown): unknown;
  function set_ui_lng(uiLngId: number): unknown;
  function get_const(uiLngId: number): unknown;
  function eval_column_const(uiLngId: number): unknown;
  function eval_column_name(code: string, listElem: unknown): string;
  function obtain_ui_lngs(): unknown;
  function compare_versions(version: unknown, curVersion: unknown): unknown;
  function verify_disp_object_blocks(source: unknown): unknown;
  function delete_resource(resource: Object, strictDelete: boolean): unknown;
  function delete_url_on_server(url: string): unknown;
  function init_view(sourceTarget: unknown): unknown;
  function get_log_email_errors(dtLastDate: Date | string): string;
  function get_border_panel_object(borderPanel: Object): Object;
  function open_dlg_global_settings(selTab: string): unknown;
  function check_doc_screen_access(topElem: unknown): unknown;
  function check_access_block_rights(accessBlock: string, right: string, user: number | CurUser): boolean;
  function obtain_shared_list_elem(listPath: string, primaryKey: string, listElem: XmlElem<unknown> | string): void;
  function delete_shared_list_elem(listPath: string, primaryKey: string): unknown;
  function save_cached_doc(param: XmlDocument): void;
  function trigger_onsavedoc(doc: XmlDocument): void;
  function check_std(objectTopElem: XmlTopElem): void | never;
  function list_edit_open_select(list: ListItem, params: Object, target: XmlElem<unknown>): void | never;
  function get_columns_array_by_field(fldChild: unknown, arrColumns: unknown[]): unknown;
  function server_on_init(topElem: unknown): unknown;
  function server_on_app_init(topElem: unknown): unknown;
  function set_next_coding(objectTargetTopElem: XmlTopElem, codingId: number | null): boolean;
  function ask_options_activate_objects_to_persons(type: string, arrValues: unknown[]): unknown;
  function ask_options_activate_qualifications_to_persons(assignment: boolean): unknown;
  function activate_objects_to_persons(taskId: string, type: string, objectIds: string, personIds: string, params: Object): unknown;
  function assign_qualifications_to_objects(taskId: string, type: string, objectIds: string, params: Object): unknown;
  function activate_to_objects(taskId: string, type: string, objectIds: string, params: Object): unknown;
  function check_task(taskId: string, retTarget: Object, request: unknown): unknown;
  function init_task(params: Object, delay: number): unknown;
  function init_task_data(taskInfoTopElem: XmlTopElem, delay: number): unknown;
  function start_task(taskId: string, methodName: string, methodParams: Object): unknown;
  function start_task_data(taskId: string, methodName: string, methodParams: Object): unknown;
  function get_task(taskId: string): unknown;
  function get_task_data(taskId: string): unknown;
  function set_task(taskId: string, taskInfoTopElem: XmlTopElem): unknown;
  function set_task_data(taskId: string, taskInfoTopElem: XmlTopElem): unknown;
  function get_tasks(taskList: string): unknown;
  function get_tasks_data(taskList: string): unknown;
  function set_task_field(taskId: string, fieldName: string, fieldValue: string): unknown;
  function set_task_field_data(taskId: string, fieldName: string, fieldValue: string): unknown;
  function remove_task(taskId: string): unknown;
  function remove_task_data(taskId: string): unknown;
  function set_message_task(taskId: string, params: Object): unknown;
  function return_message_task(taskId: string, params: Object): unknown;
  function show_massage_task(taskInfo: Object): unknown;
  function start_task_progress(methodName: string, methodParams: Object, params: Object): unknown;
  function recover_task_progress(): unknown;
  function set_progress_info(taskId: string, params: Object): unknown;
  function return_progress_info(taskId: string, params: Object): unknown;
  function catalog_resave(taskId: string, catalogName: string, dataFlag: boolean, idFlag: boolean): unknown;
  function get_all_block_access_str(): unknown;
  function get_all_block_read_access_str(): unknown;
  function check_all_block_objects_access(catalogName: string, can: string): unknown;
  function check_objects_access(parentObjectsAccess: string, catalogName: string, can: string): unknown;
  function check_access_blocks_by_catalog_name(accessBlocks: string, catalogName: string, can: string): string;
  function check_user_by_catalog_name(userAccess: Object, catalogName: string, can: string): string;
  function check_cur_user_access_blocks_by_catalog_name(catalogName: string, can: string): boolean;
  function check_cur_user_access_blocks(accessBloc: string, can: string): boolean;
  function check_cur_user_access_applications_by_catalog_name(catalogName: string, curUser: CurUser, contentAccess: Object, canElem: string): boolean;
  function get_admin_init_server_data(): unknown;
  function enable_logs_server(): unknown;
  function validate_blog_entry_comments(object: Object): unknown;
  function call_server_method(libName: string, methodName: string, arrParams: unknown[]): unknown;
  function exec_amgr_code(script: string): string;
  function navigate_view(frame: string, url: string): unknown;
  function navigate_list(url: string, type: string): unknown;
  function get_view_url(catalogName: string, urlQuery: string): unknown;
  function get_task_result_num(result: string): unknown;
  function get_callback_tasks(raramTopElem: XmlTopElem): unknown;
  function check_content_access(contentAccess: Object, catalogName: string, objectId: number, accessType: string): unknown;
  function save_doc_screen(topElem: unknown): unknown;
  function set_view_templates(topElem: unknown): unknown;
  function get_field_path(fld: unknown): unknown;
  function create_package_objects(fldPackage: unknown): unknown;
  function disp_block(blockName: string): unknown;
  function create_resource_admin(url: string, sourceTopElem: XmlTopElem, screen: unknown): unknown;
  function get_main_screen(): unknown;
  function get_loop_array(topElem: unknown, list: unknown, dispRoles: boolean, dispFilter: boolean, dispHier: boolean, arrSelRows: unknown[], parenId: number, searchType: string, remoteCollectionId: number, startPos: number, pageSize: number): unknown;
  function navigate_access_block(id: string, type: string, screenType: string): unknown;
  function get_access_block_items(fldAccessBlock: unknown): unknown;
  function set_cur_user_content_first_catalog_url(tabBlockType: string, objectId: number): unknown;
  function binary_load_from_url(fldTarget: unknown, url: string, b64encode: unknown): unknown;
  function run_view_action(topElem: unknown, screen: Object, grIdItemName: string): unknown;
  function convert_exec_code(fldExecTarget: unknown, fldUrlTarget: unknown, fldTextTarget: unknown): string;
  function convert_host_auth(topElem: unknown): unknown;
  function foreign_elem_title(fldSource: unknown, fieldName: string, defauldText: string): unknown;
  let menu_arrs_env: XmlElem<unknown | null>;
  function get_menu_blocks(): unknown;
  function get_object_source_server(objectId: number): unknown;
  function calculate_statistic_rec_obj(statisticRecId: number, objectId: number, personId: number): unknown;
  function evaluate_remote_collection_obj(remoteCollection: Object, objectId: number, personId: number, collectionParams: Object, startPos: number, pageSize: number): unknown;
  function eval_menu_remote_action(list: Object, listElemAction: unknown, screen: Object): unknown;
  function eval_remote_action_step(remoteActionId: number, params: Object): unknown;
  function eval_remote_action(remoteActionId: Object, params: Object, fldTopElem: unknown, screen: Object, dispType: string): unknown;
  function get_remote_actions_by_cur_application(catalogName: string, viewConfigurationId: number): unknown;
  function get_element_property(elem: Object, propertyName: string, altPropertyName: string, hasValue: boolean): unknown;
  function disp_application_view_configuration(applicationTopElem: XmlTopElem, viewConfigurationId: string, elemType: string, menuElem: Object, noTab: boolean, onlyUrl: boolean): unknown;
  function disp_application_complex_block(blockId: string, noTab: boolean, onlyUrl: boolean): unknown;
  function update_access_blocks_doc_types(fldAccessBlocks: unknown): unknown;
  function update_claims_by_object(objectId: Object, objectType: string, claimTypes: string): unknown;
  function get_doc_screen_wvars(doc: XmlDocument): unknown;
  function evaluate_convert_post(lastVersion: string): unknown;
}
