name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check version
        run: ./scripts/check-version.sh

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Check for changes after npm i
        run: "[[ `git status --porcelain` ]] && exit 1 || exit 0"

      - name: Check
        run: npm run check
