name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Install
        run: npm install

      - name: Check for changes after npm i
        run: "[[ `git status --porcelain` ]] && exit 1 || exit 0"

      - name: Check
        run: npm run check
