name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version
        run: |
          localVersion=$(cat package.json | jq -r '.version')
          masterVersion=$(git show origin/main:package.json | jq -r '.version')
          [ "${localVersion}" = "`echo -e "${localVersion}\n${masterVersion}" | sort -V | head -n1`" ] && echo 'Package version should be upgraded' && exit 1 || exit 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Check
        run: npm run check
