name: PR check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  Check:
    uses: ./.github/workflows/check.yml
  CheckVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install
        run: npm ci
      - name: Check version
        run: |
          localVersion=$(cat package.json | jq -r '.version')
          masterVersion=$(git show origin/main:package.json | jq -r '.version')
          [ "${localVersion}" = "`echo -e "${localVersion}\n${masterVersion}" | sort -V | head -n1`" ] && echo 'Package version should be upgraded' && exit 1 || exit 0