name: Publishing package

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 25
      - run: npm ci
      - run: npm run check
      - run: npm publish
